openapi: "3.0.0"
info:
  title: Sample Go App
  version: 1.0.0
paths:
  /delay:
    get:
      summary: Respond after a short delay
      operationId: delay
      responses:
        '200':
          description: A blank response
  /dog:
    get:
      summary: Gets all dogs
      responses:
        '200':
          description: A list of all dogs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dogs"
  /dog/watch:
    get:
      summary: Start a SSE stream for changes to dogs
      responses:
        '200':
          description: A SSE stream that sends a full Dog object as JSON whenever an update has occurred (location change, etc)
          content:
            text/event-stream:
              schema:
                $ref: "#/components/schemas/Dog"
components:
  schemas:
    Dog:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        location:
          type: string
    Dogs:
      type: array
      items:
        $ref: "#/components/schemas/Dog"

